# Generated by Django 3.2 on 2023-01-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='channel_id',
            field=models.CharField(default='asd', max_length=16),
            preserve_default=False,
        ),
    ]
